/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WalletModel from './WalletModel';

/**
 * The AuthGame200ResponseAllOf model module.
 * @module model/AuthGame200ResponseAllOf
 * @version 1.4.0
 */
class AuthGame200ResponseAllOf {
    /**
     * Constructs a new <code>AuthGame200ResponseAllOf</code>.
     * @alias module:model/AuthGame200ResponseAllOf
     */
    constructor() { 
        
        AuthGame200ResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthGame200ResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthGame200ResponseAllOf} obj Optional instance to populate.
     * @return {module:model/AuthGame200ResponseAllOf} The populated <code>AuthGame200ResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthGame200ResponseAllOf();

            if (data.hasOwnProperty('wallet')) {
                obj['wallet'] = WalletModel.constructFromObject(data['wallet']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/WalletModel} wallet
 */
AuthGame200ResponseAllOf.prototype['wallet'] = undefined;






export default AuthGame200ResponseAllOf;

