/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BurnCollectionItemRequest model module.
 * @module model/BurnCollectionItemRequest
 * @version 1.2.1
 */
class BurnCollectionItemRequest {
    /**
     * Constructs a new <code>BurnCollectionItemRequest</code>.
     * @alias module:model/BurnCollectionItemRequest
     * @param quantity {Number} The quantity of the collectionItemId to burn.
     */
    constructor(quantity) { 
        
        BurnCollectionItemRequest.initialize(this, quantity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, quantity) { 
        obj['quantity'] = quantity;
    }

    /**
     * Constructs a <code>BurnCollectionItemRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BurnCollectionItemRequest} obj Optional instance to populate.
     * @return {module:model/BurnCollectionItemRequest} The populated <code>BurnCollectionItemRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BurnCollectionItemRequest();

            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The quantity of the collectionItemId to burn.
 * @member {Number} quantity
 */
BurnCollectionItemRequest.prototype['quantity'] = undefined;






export default BurnCollectionItemRequest;

