/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContractModel from './ContractModel';
import CreateCurrency200ResponseAllOfContractAllOf from './CreateCurrency200ResponseAllOfContractAllOf';
import TransactionModel from './TransactionModel';

/**
 * The CreateCurrency200ResponseAllOfContract model module.
 * @module model/CreateCurrency200ResponseAllOfContract
 * @version 1.0.0
 */
class CreateCurrency200ResponseAllOfContract {
    /**
     * Constructs a new <code>CreateCurrency200ResponseAllOfContract</code>.
     * @alias module:model/CreateCurrency200ResponseAllOfContract
     * @implements module:model/ContractModel
     * @implements module:model/CreateCurrency200ResponseAllOfContractAllOf
     */
    constructor() { 
        ContractModel.initialize(this);CreateCurrency200ResponseAllOfContractAllOf.initialize(this);
        CreateCurrency200ResponseAllOfContract.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateCurrency200ResponseAllOfContract</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCurrency200ResponseAllOfContract} obj Optional instance to populate.
     * @return {module:model/CreateCurrency200ResponseAllOfContract} The populated <code>CreateCurrency200ResponseAllOfContract</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCurrency200ResponseAllOfContract();
            ContractModel.constructFromObject(data, obj);
            CreateCurrency200ResponseAllOfContractAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('gameId')) {
                obj['gameId'] = ApiClient.convertToType(data['gameId'], 'String');
            }
            if (data.hasOwnProperty('chain')) {
                obj['chain'] = ApiClient.convertToType(data['chain'], 'String');
            }
            if (data.hasOwnProperty('abi')) {
                obj['abi'] = ApiClient.convertToType(data['abi'], Object);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('transactions')) {
                obj['transactions'] = ApiClient.convertToType(data['transactions'], [TransactionModel]);
            }
        }
        return obj;
    }


}

/**
 * This field has not had a description added.
 * @member {String} id
 */
CreateCurrency200ResponseAllOfContract.prototype['id'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} gameId
 */
CreateCurrency200ResponseAllOfContract.prototype['gameId'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} chain
 */
CreateCurrency200ResponseAllOfContract.prototype['chain'] = undefined;

/**
 * This field has not had a description added.
 * @member {Object} abi
 */
CreateCurrency200ResponseAllOfContract.prototype['abi'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} type
 */
CreateCurrency200ResponseAllOfContract.prototype['type'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} address
 */
CreateCurrency200ResponseAllOfContract.prototype['address'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} updatedAt
 */
CreateCurrency200ResponseAllOfContract.prototype['updatedAt'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} createdAt
 */
CreateCurrency200ResponseAllOfContract.prototype['createdAt'] = undefined;

/**
 * @member {Array.<module:model/TransactionModel>} transactions
 */
CreateCurrency200ResponseAllOfContract.prototype['transactions'] = undefined;


// Implement ContractModel interface:
/**
 * This field has not had a description added.
 * @member {String} id
 */
ContractModel.prototype['id'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} gameId
 */
ContractModel.prototype['gameId'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} chain
 */
ContractModel.prototype['chain'] = undefined;
/**
 * This field has not had a description added.
 * @member {Object} abi
 */
ContractModel.prototype['abi'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} type
 */
ContractModel.prototype['type'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} address
 */
ContractModel.prototype['address'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} updatedAt
 */
ContractModel.prototype['updatedAt'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} createdAt
 */
ContractModel.prototype['createdAt'] = undefined;
// Implement CreateCurrency200ResponseAllOfContractAllOf interface:
/**
 * @member {Array.<module:model/TransactionModel>} transactions
 */
CreateCurrency200ResponseAllOfContractAllOf.prototype['transactions'] = undefined;




export default CreateCurrency200ResponseAllOfContract;

