/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProfilePermissionsValue from './ProfilePermissionsValue';

/**
 * The CreateProfilePlayerRequest model module.
 * @module model/CreateProfilePlayerRequest
 * @version 1.5.1
 */
class CreateProfilePlayerRequest {
    /**
     * Constructs a new <code>CreateProfilePlayerRequest</code>.
     * @alias module:model/CreateProfilePlayerRequest
     * @param username {String} The username to assign to the created player.
     */
    constructor(username) { 
        
        CreateProfilePlayerRequest.initialize(this, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username) { 
        obj['username'] = username;
    }

    /**
     * Constructs a <code>CreateProfilePlayerRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateProfilePlayerRequest} obj Optional instance to populate.
     * @return {module:model/CreateProfilePlayerRequest} The populated <code>CreateProfilePlayerRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateProfilePlayerRequest();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], {'String': ProfilePermissionsValue});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateProfilePlayerRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateProfilePlayerRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateProfilePlayerRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}

CreateProfilePlayerRequest.RequiredProperties = ["username"];

/**
 * The username to assign to the created player.
 * @member {String} username
 */
CreateProfilePlayerRequest.prototype['username'] = undefined;

/**
 * A properly formatted permissions object that validates against the MetaFab profile permissions schema.
 * @member {Object.<String, module:model/ProfilePermissionsValue>} permissions
 */
CreateProfilePlayerRequest.prototype['permissions'] = undefined;






export default CreateProfilePlayerRequest;

