/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CollectionModel from './CollectionModel';
import ContractModel from './ContractModel';
import GetCollections200ResponseInnerAllOf from './GetCollections200ResponseInnerAllOf';

/**
 * The GetCollections200ResponseInner model module.
 * @module model/GetCollections200ResponseInner
 * @version 1.5.1
 */
class GetCollections200ResponseInner {
    /**
     * Constructs a new <code>GetCollections200ResponseInner</code>.
     * @alias module:model/GetCollections200ResponseInner
     * @implements module:model/CollectionModel
     * @implements module:model/GetCollections200ResponseInnerAllOf
     */
    constructor() { 
        CollectionModel.initialize(this);GetCollections200ResponseInnerAllOf.initialize(this);
        GetCollections200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetCollections200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetCollections200ResponseInner} obj Optional instance to populate.
     * @return {module:model/GetCollections200ResponseInner} The populated <code>GetCollections200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCollections200ResponseInner();
            CollectionModel.constructFromObject(data, obj);
            GetCollections200ResponseInnerAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('gameId')) {
                obj['gameId'] = ApiClient.convertToType(data['gameId'], 'String');
            }
            if (data.hasOwnProperty('contractId')) {
                obj['contractId'] = ApiClient.convertToType(data['contractId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('contract')) {
                obj['contract'] = ContractModel.constructFromObject(data['contract']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetCollections200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetCollections200ResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['gameId'] && !(typeof data['gameId'] === 'string' || data['gameId'] instanceof String)) {
            throw new Error("Expected the field `gameId` to be a primitive type in the JSON string but got " + data['gameId']);
        }
        // ensure the json data is a string
        if (data['contractId'] && !(typeof data['contractId'] === 'string' || data['contractId'] instanceof String)) {
            throw new Error("Expected the field `contractId` to be a primitive type in the JSON string but got " + data['contractId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['updatedAt'] && !(typeof data['updatedAt'] === 'string' || data['updatedAt'] instanceof String)) {
            throw new Error("Expected the field `updatedAt` to be a primitive type in the JSON string but got " + data['updatedAt']);
        }
        // ensure the json data is a string
        if (data['createdAt'] && !(typeof data['createdAt'] === 'string' || data['createdAt'] instanceof String)) {
            throw new Error("Expected the field `createdAt` to be a primitive type in the JSON string but got " + data['createdAt']);
        }
        // validate the optional field `contract`
        if (data['contract']) { // data not null
          ContractModel.validateJSON(data['contract']);
        }

        return true;
    }


}



/**
 * This field has not had a description added.
 * @member {String} id
 */
GetCollections200ResponseInner.prototype['id'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} gameId
 */
GetCollections200ResponseInner.prototype['gameId'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} contractId
 */
GetCollections200ResponseInner.prototype['contractId'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} name
 */
GetCollections200ResponseInner.prototype['name'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} updatedAt
 */
GetCollections200ResponseInner.prototype['updatedAt'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} createdAt
 */
GetCollections200ResponseInner.prototype['createdAt'] = undefined;

/**
 * @member {module:model/ContractModel} contract
 */
GetCollections200ResponseInner.prototype['contract'] = undefined;


// Implement CollectionModel interface:
/**
 * This field has not had a description added.
 * @member {String} id
 */
CollectionModel.prototype['id'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} gameId
 */
CollectionModel.prototype['gameId'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} contractId
 */
CollectionModel.prototype['contractId'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} name
 */
CollectionModel.prototype['name'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} updatedAt
 */
CollectionModel.prototype['updatedAt'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} createdAt
 */
CollectionModel.prototype['createdAt'] = undefined;
// Implement GetCollections200ResponseInnerAllOf interface:
/**
 * @member {module:model/ContractModel} contract
 */
GetCollections200ResponseInnerAllOf.prototype['contract'] = undefined;




export default GetCollections200ResponseInner;

