/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProfilePermissionsValue from './ProfilePermissionsValue';

/**
 * The UpdateProfilePlayerRequest model module.
 * @module model/UpdateProfilePlayerRequest
 * @version 1.5.1
 */
class UpdateProfilePlayerRequest {
    /**
     * Constructs a new <code>UpdateProfilePlayerRequest</code>.
     * @alias module:model/UpdateProfilePlayerRequest
     */
    constructor() { 
        
        UpdateProfilePlayerRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateProfilePlayerRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateProfilePlayerRequest} obj Optional instance to populate.
     * @return {module:model/UpdateProfilePlayerRequest} The populated <code>UpdateProfilePlayerRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateProfilePlayerRequest();

            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], {'String': ProfilePermissionsValue});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateProfilePlayerRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateProfilePlayerRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * A properly formatted permissions object that validates against the MetaFab profile permissions schema.
 * @member {Object.<String, module:model/ProfilePermissionsValue>} permissions
 */
UpdateProfilePlayerRequest.prototype['permissions'] = undefined;






export default UpdateProfilePlayerRequest;

