/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateGame200ResponseAllOf model module.
 * @module model/UpdateGame200ResponseAllOf
 * @version 1.5.1
 */
class UpdateGame200ResponseAllOf {
    /**
     * Constructs a new <code>UpdateGame200ResponseAllOf</code>.
     * @alias module:model/UpdateGame200ResponseAllOf
     */
    constructor() { 
        
        UpdateGame200ResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateGame200ResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateGame200ResponseAllOf} obj Optional instance to populate.
     * @return {module:model/UpdateGame200ResponseAllOf} The populated <code>UpdateGame200ResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateGame200ResponseAllOf();

            if (data.hasOwnProperty('walletDecryptKey')) {
                obj['walletDecryptKey'] = ApiClient.convertToType(data['walletDecryptKey'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateGame200ResponseAllOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateGame200ResponseAllOf</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['walletDecryptKey'] && !(typeof data['walletDecryptKey'] === 'string' || data['walletDecryptKey'] instanceof String)) {
            throw new Error("Expected the field `walletDecryptKey` to be a primitive type in the JSON string but got " + data['walletDecryptKey']);
        }

        return true;
    }


}



/**
 * This field has not had a description added.
 * @member {String} walletDecryptKey
 */
UpdateGame200ResponseAllOf.prototype['walletDecryptKey'] = undefined;






export default UpdateGame200ResponseAllOf;

