/**
 * MetaFab API
 * Documentation for the MetaFab API. Complete API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CurrencyModel from './CurrencyModel';
import V1CurrenciesGet200ResponseAllOf from './V1CurrenciesGet200ResponseAllOf';
import V1CurrenciesGet200ResponseAllOfContract from './V1CurrenciesGet200ResponseAllOfContract';

/**
 * The V1CurrenciesGet200Response model module.
 * @module model/V1CurrenciesGet200Response
 * @version 1.0.0
 */
class V1CurrenciesGet200Response {
    /**
     * Constructs a new <code>V1CurrenciesGet200Response</code>.
     * @alias module:model/V1CurrenciesGet200Response
     * @implements module:model/CurrencyModel
     * @implements module:model/V1CurrenciesGet200ResponseAllOf
     */
    constructor() { 
        CurrencyModel.initialize(this);V1CurrenciesGet200ResponseAllOf.initialize(this);
        V1CurrenciesGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1CurrenciesGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1CurrenciesGet200Response} obj Optional instance to populate.
     * @return {module:model/V1CurrenciesGet200Response} The populated <code>V1CurrenciesGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1CurrenciesGet200Response();
            CurrencyModel.constructFromObject(data, obj);
            V1CurrenciesGet200ResponseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('gameId')) {
                obj['gameId'] = ApiClient.convertToType(data['gameId'], 'String');
            }
            if (data.hasOwnProperty('contractId')) {
                obj['contractId'] = ApiClient.convertToType(data['contractId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('supplyCap')) {
                obj['supplyCap'] = ApiClient.convertToType(data['supplyCap'], 'Number');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('contract')) {
                obj['contract'] = V1CurrenciesGet200ResponseAllOfContract.constructFromObject(data['contract']);
            }
        }
        return obj;
    }


}

/**
 * This field has not had a description added.
 * @member {String} id
 */
V1CurrenciesGet200Response.prototype['id'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} gameId
 */
V1CurrenciesGet200Response.prototype['gameId'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} contractId
 */
V1CurrenciesGet200Response.prototype['contractId'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} name
 */
V1CurrenciesGet200Response.prototype['name'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} symbol
 */
V1CurrenciesGet200Response.prototype['symbol'] = undefined;

/**
 * This field has not had a description added.
 * @member {Number} supplyCap
 */
V1CurrenciesGet200Response.prototype['supplyCap'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} updatedAt
 */
V1CurrenciesGet200Response.prototype['updatedAt'] = undefined;

/**
 * This field has not had a description added.
 * @member {String} createdAt
 */
V1CurrenciesGet200Response.prototype['createdAt'] = undefined;

/**
 * @member {module:model/V1CurrenciesGet200ResponseAllOfContract} contract
 */
V1CurrenciesGet200Response.prototype['contract'] = undefined;


// Implement CurrencyModel interface:
/**
 * This field has not had a description added.
 * @member {String} id
 */
CurrencyModel.prototype['id'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} gameId
 */
CurrencyModel.prototype['gameId'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} contractId
 */
CurrencyModel.prototype['contractId'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} name
 */
CurrencyModel.prototype['name'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} symbol
 */
CurrencyModel.prototype['symbol'] = undefined;
/**
 * This field has not had a description added.
 * @member {Number} supplyCap
 */
CurrencyModel.prototype['supplyCap'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} updatedAt
 */
CurrencyModel.prototype['updatedAt'] = undefined;
/**
 * This field has not had a description added.
 * @member {String} createdAt
 */
CurrencyModel.prototype['createdAt'] = undefined;
// Implement V1CurrenciesGet200ResponseAllOf interface:
/**
 * @member {module:model/V1CurrenciesGet200ResponseAllOfContract} contract
 */
V1CurrenciesGet200ResponseAllOf.prototype['contract'] = undefined;




export default V1CurrenciesGet200Response;

