/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionModel from './TransactionModel';

/**
 * The V1CurrenciesGet200ResponseAllOfContractAllOf model module.
 * @module model/V1CurrenciesGet200ResponseAllOfContractAllOf
 * @version 1.0.0
 */
class V1CurrenciesGet200ResponseAllOfContractAllOf {
    /**
     * Constructs a new <code>V1CurrenciesGet200ResponseAllOfContractAllOf</code>.
     * @alias module:model/V1CurrenciesGet200ResponseAllOfContractAllOf
     */
    constructor() { 
        
        V1CurrenciesGet200ResponseAllOfContractAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1CurrenciesGet200ResponseAllOfContractAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1CurrenciesGet200ResponseAllOfContractAllOf} obj Optional instance to populate.
     * @return {module:model/V1CurrenciesGet200ResponseAllOfContractAllOf} The populated <code>V1CurrenciesGet200ResponseAllOfContractAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1CurrenciesGet200ResponseAllOfContractAllOf();

            if (data.hasOwnProperty('transactions')) {
                obj['transactions'] = ApiClient.convertToType(data['transactions'], [TransactionModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TransactionModel>} transactions
 */
V1CurrenciesGet200ResponseAllOfContractAllOf.prototype['transactions'] = undefined;






export default V1CurrenciesGet200ResponseAllOfContractAllOf;

