/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateWalletSignatureRequest from '../model/CreateWalletSignatureRequest';
import TransactionModel from '../model/TransactionModel';
import WalletModel from '../model/WalletModel';

/**
* Wallets service.
* @module api/WalletsApi
* @version 1.5.1
*/
export default class WalletsApi {

    /**
    * Constructs a new WalletsApi. 
    * @alias module:api/WalletsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create wallet signature
     * Creates a wallet signature from a plaintext message using the wallet for the provided walletId and walletDecryptKey. Wallet signatures cannot be generated for EOA wallets.
     * @param {String} walletId Any wallet id within the MetaFab platform.
     * @param {String} xWalletDecryptKey The `walletDecryptKey` for the provided `walletId`.
     * @param {module:model/CreateWalletSignatureRequest} createWalletSignatureRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link String} and HTTP response
     */
    createWalletSignatureWithHttpInfo(walletId, xWalletDecryptKey, createWalletSignatureRequest) {
      let postBody = createWalletSignatureRequest;
      // verify the required parameter 'walletId' is set
      if (walletId === undefined || walletId === null) {
        throw new Error("Missing the required parameter 'walletId' when calling createWalletSignature");
      }
      // verify the required parameter 'xWalletDecryptKey' is set
      if (xWalletDecryptKey === undefined || xWalletDecryptKey === null) {
        throw new Error("Missing the required parameter 'xWalletDecryptKey' when calling createWalletSignature");
      }
      // verify the required parameter 'createWalletSignatureRequest' is set
      if (createWalletSignatureRequest === undefined || createWalletSignatureRequest === null) {
        throw new Error("Missing the required parameter 'createWalletSignatureRequest' when calling createWalletSignature");
      }

      let pathParams = {
        'walletId': walletId
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Wallet-Decrypt-Key': xWalletDecryptKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/v1/wallets/{walletId}/signatures', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create wallet signature
     * Creates a wallet signature from a plaintext message using the wallet for the provided walletId and walletDecryptKey. Wallet signatures cannot be generated for EOA wallets.
     * @param {String} walletId Any wallet id within the MetaFab platform.
     * @param {String} xWalletDecryptKey The `walletDecryptKey` for the provided `walletId`.
     * @param {module:model/CreateWalletSignatureRequest} createWalletSignatureRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link String}
     */
    createWalletSignature(walletId, xWalletDecryptKey, createWalletSignatureRequest) {
      return this.createWalletSignatureWithHttpInfo(walletId, xWalletDecryptKey, createWalletSignatureRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get wallet
     * Returns a wallet object for the provided walletId.
     * @param {String} walletId Any wallet id within the MetaFab platform.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/WalletModel} and HTTP response
     */
    getWalletWithHttpInfo(walletId) {
      let postBody = null;
      // verify the required parameter 'walletId' is set
      if (walletId === undefined || walletId === null) {
        throw new Error("Missing the required parameter 'walletId' when calling getWallet");
      }

      let pathParams = {
        'walletId': walletId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = WalletModel;
      return this.apiClient.callApi(
        '/v1/wallets/{walletId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get wallet
     * Returns a wallet object for the provided walletId.
     * @param {String} walletId Any wallet id within the MetaFab platform.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/WalletModel}
     */
    getWallet(walletId) {
      return this.getWalletWithHttpInfo(walletId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get wallet balances
     * Returns the current native token balance for all chains supported by MetaFab for the provided walletId. This includes balances like Eth, Matic and other native tokens from chains MetaFab supports.
     * @param {String} walletId Any wallet id within the MetaFab platform.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object.<String, {String: Number}>} and HTTP response
     */
    getWalletBalancesWithHttpInfo(walletId) {
      let postBody = null;
      // verify the required parameter 'walletId' is set
      if (walletId === undefined || walletId === null) {
        throw new Error("Missing the required parameter 'walletId' when calling getWalletBalances");
      }

      let pathParams = {
        'walletId': walletId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = {'String': 'Number'};
      return this.apiClient.callApi(
        '/v1/wallets/{walletId}/balances', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get wallet balances
     * Returns the current native token balance for all chains supported by MetaFab for the provided walletId. This includes balances like Eth, Matic and other native tokens from chains MetaFab supports.
     * @param {String} walletId Any wallet id within the MetaFab platform.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object.<String, {String: Number}>}
     */
    getWalletBalances(walletId) {
      return this.getWalletBalancesWithHttpInfo(walletId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get wallet transactions
     * Returns an array of MetaFab initiated transactions performed by the provided walletId. Transactions returned are ordered chronologically from newest to oldest.
     * @param {String} walletId Any wallet id within the MetaFab platform.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/TransactionModel>} and HTTP response
     */
    getWalletTransactionsWithHttpInfo(walletId) {
      let postBody = null;
      // verify the required parameter 'walletId' is set
      if (walletId === undefined || walletId === null) {
        throw new Error("Missing the required parameter 'walletId' when calling getWalletTransactions");
      }

      let pathParams = {
        'walletId': walletId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TransactionModel];
      return this.apiClient.callApi(
        '/v1/wallets/{walletId}/transactions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get wallet transactions
     * Returns an array of MetaFab initiated transactions performed by the provided walletId. Transactions returned are ordered chronologically from newest to oldest.
     * @param {String} walletId Any wallet id within the MetaFab platform.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/TransactionModel>}
     */
    getWalletTransactions(walletId) {
      return this.getWalletTransactionsWithHttpInfo(walletId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
