/**
 * MetaFab API
 * Documentation for the MetaFab API. Complete API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetaFabApi);
  }
}(this, function(expect, MetaFabApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetaFabApi.GameModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GameModel', function() {
    it('should create an instance of GameModel', function() {
      // uncomment below and update the code to test GameModel
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be.a(MetaFabApi.GameModel);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be();
    });

    it('should have the property walletId (base name: "walletId")', function() {
      // uncomment below and update the code to test the property walletId
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be();
    });

    it('should have the property fundingWalletId (base name: "fundingWalletId")', function() {
      // uncomment below and update the code to test the property fundingWalletId
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be();
    });

    it('should have the property rpcs (base name: "rpcs")', function() {
      // uncomment below and update the code to test the property rpcs
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be();
    });

    it('should have the property publishedKey (base name: "publishedKey")', function() {
      // uncomment below and update the code to test the property publishedKey
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be();
    });

    it('should have the property secretKey (base name: "secretKey")', function() {
      // uncomment below and update the code to test the property secretKey
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new MetaFabApi.GameModel();
      //expect(instance).to.be();
    });

  });

}));
