/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetafabJavascript);
  }
}(this, function(expect, MetafabJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SetLootboxManagerLootboxRequest', function() {
    it('should create an instance of SetLootboxManagerLootboxRequest', function() {
      // uncomment below and update the code to test SetLootboxManagerLootboxRequest
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be.a(MetafabJavascript.SetLootboxManagerLootboxRequest);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

    it('should have the property inputCollectionAddress (base name: "inputCollectionAddress")', function() {
      // uncomment below and update the code to test the property inputCollectionAddress
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

    it('should have the property inputCollectionId (base name: "inputCollectionId")', function() {
      // uncomment below and update the code to test the property inputCollectionId
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

    it('should have the property inputCollectionItemIds (base name: "inputCollectionItemIds")', function() {
      // uncomment below and update the code to test the property inputCollectionItemIds
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

    it('should have the property inputCollectionItemAmounts (base name: "inputCollectionItemAmounts")', function() {
      // uncomment below and update the code to test the property inputCollectionItemAmounts
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

    it('should have the property outputCollectionAddress (base name: "outputCollectionAddress")', function() {
      // uncomment below and update the code to test the property outputCollectionAddress
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

    it('should have the property outputCollectionId (base name: "outputCollectionId")', function() {
      // uncomment below and update the code to test the property outputCollectionId
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

    it('should have the property outputCollectionItemIds (base name: "outputCollectionItemIds")', function() {
      // uncomment below and update the code to test the property outputCollectionItemIds
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

    it('should have the property outputCollectionItemAmounts (base name: "outputCollectionItemAmounts")', function() {
      // uncomment below and update the code to test the property outputCollectionItemAmounts
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

    it('should have the property outputCollectionItemWeights (base name: "outputCollectionItemWeights")', function() {
      // uncomment below and update the code to test the property outputCollectionItemWeights
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

    it('should have the property outputTotalItems (base name: "outputTotalItems")', function() {
      // uncomment below and update the code to test the property outputTotalItems
      //var instance = new MetafabJavascript.SetLootboxManagerLootboxRequest();
      //expect(instance).to.be();
    });

  });

}));
