/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetafabJavascript);
  }
}(this, function(expect, MetafabJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetafabJavascript.ShopOffer();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShopOffer', function() {
    it('should create an instance of ShopOffer', function() {
      // uncomment below and update the code to test ShopOffer
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be.a(MetafabJavascript.ShopOffer);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property inputCollection (base name: "inputCollection")', function() {
      // uncomment below and update the code to test the property inputCollection
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property inputCollectionItemIds (base name: "inputCollectionItemIds")', function() {
      // uncomment below and update the code to test the property inputCollectionItemIds
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property inputCollectionItemAmounts (base name: "inputCollectionItemAmounts")', function() {
      // uncomment below and update the code to test the property inputCollectionItemAmounts
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property inputCurrency (base name: "inputCurrency")', function() {
      // uncomment below and update the code to test the property inputCurrency
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property inputCurrencyAmount (base name: "inputCurrencyAmount")', function() {
      // uncomment below and update the code to test the property inputCurrencyAmount
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property outputCollection (base name: "outputCollection")', function() {
      // uncomment below and update the code to test the property outputCollection
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property outputCollectionItemIds (base name: "outputCollectionItemIds")', function() {
      // uncomment below and update the code to test the property outputCollectionItemIds
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property outputCollectionItemAmounts (base name: "outputCollectionItemAmounts")', function() {
      // uncomment below and update the code to test the property outputCollectionItemAmounts
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property outputCurrency (base name: "outputCurrency")', function() {
      // uncomment below and update the code to test the property outputCurrency
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property outputCurrencyAmount (base name: "outputCurrencyAmount")', function() {
      // uncomment below and update the code to test the property outputCurrencyAmount
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property uses (base name: "uses")', function() {
      // uncomment below and update the code to test the property uses
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property maxUses (base name: "maxUses")', function() {
      // uncomment below and update the code to test the property maxUses
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdatedAt (base name: "lastUpdatedAt")', function() {
      // uncomment below and update the code to test the property lastUpdatedAt
      //var instance = new MetafabJavascript.ShopOffer();
      //expect(instance).to.be();
    });

  });

}));
