/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetafabJavascript);
  }
}(this, function(expect, MetafabJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetafabJavascript.UpdateProfilePlayer200ResponseAllOf();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateProfilePlayer200ResponseAllOf', function() {
    it('should create an instance of UpdateProfilePlayer200ResponseAllOf', function() {
      // uncomment below and update the code to test UpdateProfilePlayer200ResponseAllOf
      //var instance = new MetafabJavascript.UpdateProfilePlayer200ResponseAllOf();
      //expect(instance).to.be.a(MetafabJavascript.UpdateProfilePlayer200ResponseAllOf);
    });

    it('should have the property wallet (base name: "wallet")', function() {
      // uncomment below and update the code to test the property wallet
      //var instance = new MetafabJavascript.UpdateProfilePlayer200ResponseAllOf();
      //expect(instance).to.be();
    });

    it('should have the property custodialWallet (base name: "custodialWallet")', function() {
      // uncomment below and update the code to test the property custodialWallet
      //var instance = new MetafabJavascript.UpdateProfilePlayer200ResponseAllOf();
      //expect(instance).to.be();
    });

  });

}));
