/**
 * MetaFab API
 * Documentation for the MetaFab API. Complete API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetaFabApi);
  }
}(this, function(expect, MetaFabApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetaFabApi.ContractsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContractsApi', function() {
    describe('v1ContractsContractIdReadsGet', function() {
      it('should call v1ContractsContractIdReadsGet successfully', function(done) {
        //uncomment below and update the code to test v1ContractsContractIdReadsGet
        //instance.v1ContractsContractIdReadsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ContractsContractIdWritesPost', function() {
      it('should call v1ContractsContractIdWritesPost successfully', function(done) {
        //uncomment below and update the code to test v1ContractsContractIdWritesPost
        //instance.v1ContractsContractIdWritesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ContractsGet', function() {
      it('should call v1ContractsGet successfully', function(done) {
        //uncomment below and update the code to test v1ContractsGet
        //instance.v1ContractsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1ContractsPost', function() {
      it('should call v1ContractsPost successfully', function(done) {
        //uncomment below and update the code to test v1ContractsPost
        //instance.v1ContractsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
